name: Laravel

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
     - name: send custom message
       uses: appleboy/telegram-action@master
       with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
         <strong>Repo ${{repo.name}}</strong>
         The <b>${{ github.event_name }}</b> event triggered.
         <strong>${{ github.actor }}</strong> ${{ github.event_name }} woi.
         Dekat branch <b>${{ master_branch }}</b>
     - uses: actions/checkout@v2
       with:
        token: ${{ secrets.PUSH_TOKEN }}
     - name: Deploy to production
       uses: appleboy/ssh-action@master
       with:
        username: root
        host: 128.199.185.188
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/mukabuku && ./deploy.sh'
     
